### ISSUE TITLE
how can i

### ISSUE THREAD

**Issue by 30410B** [marijavella/hs-sr-tvtv#1]

**Comment by 30410B** [comment]
how can i use my own image to get .mat files

**Comment by 30410B** [comment]
where is the CSR function ？？

**Comment by marijavella** [comment]
To get .mat files you need to load the images in Matlab and save them as a .mat file. The CSR function is represented by R and is loaded as a matrix. Please refer to our paper (https://arxiv.org/abs/2106.07066) for all the details.

**Comment by 30410B** [comment]
Thanks for your reply ，i just met the problem‘Keyerror：outX’ in the line 50 of main.py，do you know how to solve it ?

**Comment by Keima623** [comment]
get_W()# download data from Google drive
I can not get the data from it (Max retries exceeded with url: /u/0/uc?id=1bf6kWyAgf1JSTy25xwoR9qDLWG-UQtu7&export=download (Caused by ProxyError('Cannot connect to proxy.')
https://drive.google.com/u/0/uc?id=1bf6kWyAgf1JSTy25xwoR9qDLWG-UQtu7&export=download
https://drive.google.com/u/0/uc?id=1Jfr16RWW7BiukLiyzqOEqO8A9TCLujjG&export=download
https://drive.google.com/u/0/uc?id=15vTwIRimGoUxaE9JBGhHCTvI6EglRoYq&export=download
can you give the data in it please
